feat: Update build ci/cd 💚

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,3 +27,78 @@ jobs:
     if: github.event.pull_request.draft == false
     uses: ./.github/workflows/_test_with_coverage.yml
     secrets: inherit
+        
+  analyze:
+    name: Analyze
+    if: github.event.pull_request.draft == false
+    timeout-minutes: 30
+    runs-on: ubuntu-latest
+    steps:
+      - name: ⬇️ Checkout repository
+        uses: actions/checkout@v3
+      - name: ⚙️ Setup Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          channel: 'stable'
+          cache: true
+      - name: ⚙️ Setup Melos
+        uses: bluefireteam/melos-action@v2
+      - name: ⚙️ Install dependencies for all packages
+        run: melos build:pub_get:all
+      - name: 📄 Move dummy pubspec.yaml to root
+        run: cp scripts/pubspec_template.yaml pubspec.yaml
+      - name: ⚠️ℹ️ Run Dart analysis for app package
+        uses: zgosalvez/github-actions-analyze-dart@v2.0.9
+        with:
+          working-directory: "${{github.workspace}}/packages/gamemark/"
+      - name: 📡 Run flutter analyze
+        run: |
+          cd ${{github.workspace}}/packages/
+          flutter analyze > analysis_output.txt
+        continue-on-error: true
+      - name: 📈 Check for code issues
+        id: code-issues
+        run: |
+          if grep -q "error" analysis_output.txt; then
+            echo "::error::Code analysis failed"
+            exit 1
+          else
+            echo "Code analysis passed"
+          fi
+      - name: 📄 Upload analysis results
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: analysis-results
+          path: analysis_output.txt
+
+  build:
+    name: Build Android
+    if: github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+      - name: ⬇️ Checkout repository
+        uses: actions/checkout@v3
+      - name: ⚙️ Setup Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          channel: 'stable'
+          cache: true
+      - name: ⚙️ Setup Java
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'zulu'
+          java-version: "12.x"
+          cache: 'gradle'
+        id: java
+      - name: ⚙️ Setup Melos
+        uses: bluefireteam/melos-action@v2
+      - name: ⚙️ Install dependencies for all packages
+        run: melos build:pub_get:all
+      - name: 🤖🔨 Build Android app
+        run: |
+          pushd packages/melos/
+          flutter build appbundle --debug --flavor dev -t lib/main_dev.dart
+          popd
+      
